shell = "/usr/bin/zsh"

import = [
    "~/.config/alacritty/themes/themes/hardhacker.toml"
]

[window]
padding.x = 10
padding.y = 10

decorations = "None"

opacity = 0.9
blur = true

# startup_mode = "Maximized"

[font]
normal.family = "JetBrainsMono NF"
size = 12
